name: Every Friday
on: 
  schedule:
    - cron: "0 20 * * 5"

jobs:
  build:
    runs-on: ubunty-latest
    strategy:
      matrix:
        version: [6, 7, 8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build 
        run: dotnet build Console/Console.csproj --configuration Debug


    
